name: Deploy Slate Docs

on:
  push:
    branches:
      - main  # Change to your default branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'  # Ensure this matches your Ruby version
          bundler-cache: true

      - name: Install dependencies
        run: |
          ls -la  # Debugging step to check files
          bundle config set --local path 'vendor/bundle'
          bundle install

      - name: Build Slate documentation
        run: bundle exec middleman build --clean

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Ensure this is the correct path to the built files