name: Deploy Slate Docs

on:
  push:
    branches:
      - master  #  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Ruby and Bundler
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full build-essential
          gem install bundler --user-install
          echo "$HOME/.local/share/gem/ruby/3.2.0/bin" >> $GITHUB_PATH  #  

      - name: Build Slate
        run: |
          ls -la  # Vérifier que Gemfile est bien présent
          bundle config set --local path 'vendor/bundle'  #  
          bundle install
          bundle exec middleman build --clean  #  

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  #  